"""Regenerate NETWORK_GEOMETRY.md from the current canvas constants."""
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from src.ui import canvas_gemini as canvas
from src.ui import control_panel


def render():
    values = (
        ("Surface width", canvas.WIDTH, "px"),
        ("Surface height", canvas.HEIGHT, "px"),
        ("Horizontal corridor center", canvas.H_Y, "px"),
        ("Lane width", canvas.LANE, "px"),
        ("Lanes per direction", canvas.LANES, "lanes"),
        ("Total road width", canvas.ROAD_W, "px"),
        ("Stop offset", canvas.STOP, "px"),
    )
    lines = [
        "# Current network geometry",
        "",
        "Generated by `python docs/generate_geometry_tables.py` from "
        "`src/ui/canvas_gemini.py`. Do not edit the values by hand.",
        "",
        "| Constant | Value | Unit |",
        "|---|---:|---|",
    ]
    lines += [f"| {name} | {value} | {unit} |" for name, value, unit in values]
    lines += [
        "", "| Node | X coordinate (px) |", "|---|---:|",
    ]
    lines += [f"| {chr(65 + i)} | {x} |" for i, x in enumerate(canvas.INT_X)]
    lines += [""]
    return "\n".join(lines)


def render_routes():
    lines = [
        "| Route ID | Name | Origin to destination | Waypoints | Lanes | Active | Headway | TSP | DBL | Manual dispatch |",
        "|---|---|---|---|---|---|---|---|---|---|",
    ]
    for route_id, route in control_panel.bus_routes_config.items():
        waypoints = ", ".join(f"{x}: {move}" for x, move in route.get("waypoints", {}).items())
        lanes = ", ".join(f"{x}: {lane}" for x, lane in route.get("lanes", {}).items())
        yes_no = lambda value: "Yes" if value else "No"
        lines.append(
            f"| `{route_id}` | {route['name']} | {route['origin']} to {route['destination']} "
            f"| {waypoints} | {lanes} | {yes_no(route['active'])} | {route['headway_sec']}s "
            f"| {yes_no(route['tsp_enabled'])} | {yes_no(route['dbl_enabled'])} "
            f"| {yes_no(route['manual_dispatch'])} |"
        )
    return "\n".join(lines)


if __name__ == "__main__":
    (ROOT / "docs" / "NETWORK_GEOMETRY.md").write_text(render(), encoding="utf-8")
    parameters = ROOT / "docs" / "SIMULATION_INPUT_PARAMETERS.md"
    content = parameters.read_text(encoding="utf-8")
    start, end = "<!-- BEGIN GENERATED ROUTES -->", "<!-- END GENERATED ROUTES -->"
    content = content.replace(
        "Node A = intersection 300, Node B = intersection 700",
        "Node A and Node B as listed in NETWORK_GEOMETRY.md",
    )
    if start not in content or end not in content:
        table_start = content.index("| Route ID |")
        table_end = content.index("\n\nField definitions:", table_start)
        content = content[:table_start] + start + "\n" + end + content[table_end:]
    if start in content and end in content:
        prefix, remainder = content.split(start, 1)
        _, suffix = remainder.split(end, 1)
        parameters.write_text(
            prefix + start + "\n" + render_routes() + "\n" + end + suffix,
            encoding="utf-8",
        )
